### ISSUE TITLE
作者你好，想问下您的这个项目有参考的论文吗？

### ISSUE THREAD

**Issue by QzP-QD** [joejoe233/TrafficClassification#3]
作者你好，想问下您的这个项目有参考的论文吗？如提出将流量数据转换为图片这一思路的论文，想拜读下

**Comment by joejoe233** [comment]
您好，可以参考[这篇论文](http://www.infocomm-journal.com/txxb/EN/Y2018/V39/I1/14)

**Comment by QzP-QD** [comment]
非常感谢！
